//company
export const companyRequest = 'companyRequest'
export const companySucess = 'companySucess'
export const companyError = 'companyError'
export const companyOrderState = 'companyOrderState'

//login
export const loadInitialState = 'loadInitialState'
export const userInputPhoneCode = 'userInputPhoneCode'
export const userInputPhoneNumber = 'userInputPhoneNumber'
export const registerRequest = 'registerRequest'
export const registerRequestSuccess = 'registerRequestSuccess'
export const registerRequestError = 'registerRequestError'
export const verifyRequest = 'verifyRequest'
export const verifySucess = 'verifySucess'
export const verifyError = 'verifyError'
export const loadInitialStateConfirm = 'loadInitialStateConfirm'
export const setDeviceToken = 'setDeviceToken'
//menu
export const menuRequest = 'menuRequest'
export const menuSucess = 'menuSucess'
export const menuError = 'menuError'
export const setLocation = 'setLocation'
//order
export const ordeError = 'ordeError'
export const updateOrderState = 'update_order_state'
export const doOrder = 'do_order'
export const orderRequest = 'orderRequest'
export const flushOrder = 'flush'
export const loadDataOrder = 'load_data'
export const addItemOrder = 'add_item'
export const changeItemAdditionOrder = 'change_item_addition'
export const cleanDraftOrder = 'clean_draft_order'
//dialog
export const dialogShowing = 'show'
export const dialogHiding = 'hide'
